### ISSUE TITLE
Netlib tests

### ISSUE THREAD

**Issue by dibyendumajumdar** [geoffleyland/luasimplex#1]
Hi,

Thank you for the cool project. 
I am running the netlib tests and I see some cases of failures; I was wondering if you have a list of test results that I can compare against. 

Regards

**Comment by geoffleyland** [comment]
Hi Dibyendu,

I just ran it on my machine, and results are below.  Beyond DEGEN3 nothing seems to solve.

Cheers,
Geoff


% luajit test-netlib.lua --test-dir ../../netlib/
C RSM is available
Testing netlib: fast, with ffi
Test      	 Variables	 Constraints	  Nonzeros	      Expect	    Obtained	    Abs diff	    Rel diff	  Iterations	Time (s)	Total time (s)
AFIRO     	        51	          27	       102	    -464.753	    -464.753	 2.85729e-09	 6.14798e-12	          29	  0.0026	        0.0026
SC50B     	        78	          50	       148	         -70	         -70	           0	           0	          61	  0.0014	        0.0040
SC50A     	        78	          50	       160	    -64.5751	    -64.5751	 4.35492e-10	 6.74396e-12	          60	  0.0008	        0.0048
KB2       	        68	          43	       313	     -1749.9	     -1749.9	  6.0129e-09	 3.43614e-12	          94	  0.0021	        0.0069
SC105     	       163	         105	       340	    -52.2021	    -52.2021	 2.92758e-10	 5.60817e-12	         124	  0.0043	        0.0112
ADLITTLE  	       138	          56	       424	      225495	      225495	 2.38049e-06	 1.05567e-11	         162	  0.0039	        0.0150
STOCFOR1  	       165	         117	       501	      -41132	      -41132	 4.39235e-07	 1.06787e-11	         220	  0.0081	        0.0231
BLEND     	       114	          74	       522	    -30.8121	    -30.8121	 1.84876e-10	  6.0001e-12	         151	  0.0043	        0.0274
SCAGR7    	       185	         129	       465	-2.33139e+06	-2.33139e+06	    0.569531	 2.44288e-07	         223	  0.0103	        -
SC205     	       317	         205	       665	    -52.2021	    -52.2021	 2.92772e-10	 5.60844e-12	         252	  0.0202	        0.0475
SHARE2B   	       162	          96	       777	    -415.732	    -415.732	 1.56058e-09	 3.75381e-12	         167	  0.0051	        0.0526
LOTFI     	       366	         153	      1136	    -25.2647	    -25.2647	 1.20121e-10	 4.75449e-12	         299	  0.0192	        0.0718
SHARE1B   	       253	         117	      1179	    -76589.3	    -76589.3	 1.85624e-07	 2.42363e-12	         453	  0.0177	        0.0895
BOEING2   	       305	         166	      1358	    -315.019	    -306.755	     8.26395	   0.0262332	         970	  0.0690	        -
BORE3D    	       334	         233	      1448	     1373.08	ERROR: Infeasible
SCORPION  	       466	         388	      1534	     1878.12	     1875.85	     2.27309	   0.0012103	         397	  0.1050	        -
CAPRI     	       482	         271	      1896	     2690.01	     2690.01	 3.18282e-08	  1.1832e-11	         729	  0.0824	        0.1718
BRANDY    	       303	         220	      2202	     1518.51	ERROR: Infeasible
SCAGR25   	       671	         471	      1725	-1.47534e+07	-1.47534e+07	 0.000231527	 1.56931e-11	         951	  0.3597	        0.5316
SCTAP1    	       660	         300	      1872	     1412.25	     1412.25	 1.36424e-12	 9.66006e-16	         799	  0.1240	        0.6555
ISRAEL    	       316	         174	      2443	     -896645	     -896645	 3.04473e-06	 3.39569e-12	         943	  0.0698	        0.7253
SCFXM1    	       600	         330	      2732	     18416.8	     18416.8	  3.4905e-07	 1.89528e-11	         770	  0.1415	        0.8668
BANDM     	       472	         305	      2494	    -158.628	    -152.406	     6.22216	   0.0392248	        1632	  0.2680	        -
E226      	       472	         223	      2768	    -18.7519	    -18.7519	 3.70573e-10	 1.97619e-11	         865	  0.0861	        0.9529
AGG       	       615	         488	      2862	-3.59918e+07	-5.20675e+07	 1.60757e+07	     0.44665	         641	  0.2387	        -
GROW7     	       301	         140	      2612	-4.77878e+07	-4.77878e+07	 0.000288494	 6.03698e-12	         316	  0.0147	        0.9677
ETAMACRO  	       816	         400	      2537	    -755.715	    -755.715	 1.07237e-05	 1.41902e-08	        1525	  0.3345	        1.3022
FINNIS    	      1064	         497	      2760	      172791	      123747	     49044.2	    0.283835	        2419	  0.7565	        -
SCSD1     	       760	          77	      2388	     8.66667	     8.66667	 3.33689e-11	 3.85025e-12	         325	  0.0100	        1.3121
STANDATA  	      1274	         359	      3230	      1257.7	      1257.7	 4.77485e-12	 3.79649e-15	         720	  0.1385	        1.4507
BEACONFD  	       295	         173	      3408	     33592.5	     33592.5	 1.97302e-07	  5.8734e-12	         286	  0.0210	        1.4716
STAIR     	       614	         356	      4003	    -251.267	    -251.267	 2.96356e-09	 1.17945e-11	        1028	  0.1929	        1.6645
STANDMPS  	      1274	         467	      3878	     1406.02	     1406.02	 1.59162e-12	   1.132e-15	         981	  0.3111	        1.9756
GFRD-PNC  	      1160	         616	      2445	 6.90224e+06	 6.90224e+06	 4.88134e-05	 7.07212e-12	         923	  0.5566	        2.5322
SCRS8     	      1275	         490	      3288	       904.3	     578.755	     325.545	    0.359996	        1454	  0.5329	        -
BOEING1   	       726	         351	      3827	    -335.214	ERROR: Iteration limit
MODSZK1   	      1620	         687	      3168	      320.62	ERROR: Iteration limit
TUFF      	       628	         333	      4561	    0.292148	ERROR: Iteration limit
DEGEN2    	       757	         444	      4201	    -1435.18	    -1435.18	 2.95586e-12	 2.05958e-15	        1986	  0.6561	        3.1884
FORPLAN   	       492	         161	      4634	    -664.219	ERROR: Iteration limit
AGG2      	       758	         516	      4740	-2.02393e+07	-2.02393e+07	 2.28882e-05	 1.13088e-12	         587	  0.2610	        3.4494
AGG3      	       758	         516	      4756	 1.03121e+07	 1.03121e+07	 8.92207e-05	 8.65203e-12	         596	  0.2664	        3.7158
SCFXM2    	      1200	         660	      5469	     36660.3	     36660.3	 1.30967e-10	 3.57246e-15	        1495	  0.9892	        4.7050
SHELL     	      1777	         536	      3558	 1.20883e+09	 1.20883e+09	           0	           0	        1041	  0.4626	        5.1675
PILOT4    	      1123	         410	      5264	    -2581.14	ERROR: Iteration limit
SCSD6     	      1350	         147	      4316	        50.5	        50.5	 2.62368e-10	  5.1954e-12	         654	  0.0496	        5.2172
SHIP04S   	      1506	         402	      4400	 1.79871e+06	 1.79871e+06	 4.53922e-05	 2.52359e-11	         515	  0.1667	        5.3838
SEBA      	      1036	         515	      4360	     15711.6	ERROR: Infeasible
GROW15    	       645	         300	      5620	-1.06871e+08	-1.06871e+08	  0.00357531	 3.34545e-11	         862	  0.1476	        5.5314
FFFFF800  	      1028	         524	      6401	      555680	      555680	   0.0468325	 8.42796e-08	        1468	  0.8832	        6.4146
BNL1      	      1586	         643	      5532	     1977.63	ERROR: Infeasible
PEROLD    	      1506	         625	      6148	    -9380.76	ERROR: Iteration limit
QAP8      	      1632	         912	      7296	       203.5	ERROR: Infeasible
SCFXM3    	      1800	         990	      8206	     54901.3	     54901.3	 2.46153e-07	 4.48356e-12	        2231	  3.3084	        9.7231
SHIP04L   	      2166	         402	      6380	 1.79332e+06	 1.79332e+06	 2.96438e-05	 1.65301e-11	         564	  0.1768	        9.8999
GANGES    	      1706	        1309	      6937	     -109586	     -109586	    0.627431	 5.72545e-06	        1654	  4.3219	        -
SCTAP2    	      2500	        1090	      7334	     1724.81	     1724.81	 4.28554e-08	 2.48465e-11	        3316	  6.7582	       16.6580
GROW22    	       946	         440	      8252	-1.60834e+08	-1.60834e+08	  0.00256267	 1.59336e-11	        1392	  0.4283	       17.0863
SHIP08S   	      2467	         778	      7194	  1.9201e+06	  1.9201e+06	 3.46166e-05	 1.80285e-11	        1090	  1.2450	       18.3313
MAROS     	      1966	         846	     10137	    -58063.7	ERROR: Iteration limit
STOCFOR2  	      3045	        2157	      9357	    -39024.4	    -39024.4	 1.30371e-07	 3.34075e-12	        3670	 25.2550	       43.5863
25FV47    	      1876	         821	     10705	     5501.85	ERROR: Iteration limit
SHIP12S   	      2869	        1151	      8284	 1.48924e+06	 1.48924e+06	 6.13253e-06	  4.1179e-12	        1559	  3.3620	       46.9483
SCSD8     	      2750	         397	      8584	         905	         905	 4.53542e-09	 5.01152e-12	        1730	  0.5718	       47.5201
FIT1P     	      1677	         627	      9868	     9146.38	     9146.38	 2.09529e-08	 2.29085e-12	        2843	  2.5695	       50.0896
SCTAP3    	      3340	        1480	      9734	        1424	        1424	 7.45786e-11	 5.23726e-14	        4045	 13.1671	       63.2567
SIERRA    	      2735	        1227	      8001	 1.53944e+07	 1.53944e+07	 0.000368081	 2.39101e-11	        2678	  6.0233	       69.2801
PILOTNOV  	      2446	         975	     13331	    -4497.28	ERROR: Iteration limit
CZPROB    	      3562	         929	     10708	  2.1852e+06	  2.1852e+06	  4.3428e-05	 1.98737e-11	        2755	  3.6467	       72.9268
FIT1D     	      1049	          24	     13427	    -9146.38	    -9146.38	 2.08929e-08	 2.28428e-12	        1378	  0.0576	       72.9845
SHIP08L   	      4363	         778	     12882	 1.90906e+06	 1.90906e+06	 1.08692e-05	 5.69351e-12	        1410	  1.5494	       74.5339
BNL2      	      4486	        2324	     14996	     1811.24	ERROR: Iteration limit
NESM      	      3105	         662	     13470	 1.40761e+07	  1.4076e+07	     36.5474	 2.59642e-06	        8870	  5.0860	        -
CYCLE     	      3371	        1903	     21234	    -5.22639	ERROR: Iteration limit
SHIP12L   	      5533	        1151	     16276	 1.47019e+06	 1.47019e+06	 2.92661e-05	 1.99064e-11	        2333	  5.4130	       79.9469
DEGEN3    	      2604	        1503	     25432	    -987.294	ERROR: Iteration limit
GREENBEA  	      5598	        2392	     31070	-7.24624e+07	ERROR: Iteration limit
GREENBEB  	      5598	        2392	     31070	-4.30215e+06	ERROR: Iteration limit
80BAU3B   	     12061	        2262	     23264	      987232	ERROR: Iteration limit
TRUSS     	      8806	        1000	     27836	      458816	ERROR: Iteration limit
D2Q06C    	      5831	        2171	     33081	      122784	ERROR: Iteration limit
WOODW     	      8418	        1098	     37487	     1.30448	ERROR: Iteration limit
QAP12     	      8856	        3192	     38304	     522.894	ERROR: Iteration limit
D6CUBE    	ERROR: ./luasimplex/mps.lua:51: attempt to index local 'r' (a nil value)
PILOT     	      4860	        1441	     44375	    -557.404	ERROR: Iteration limit
DFL001    	     12230	        6071	     35632	 1.12664e+07



> On 11/07/2021, at 11:31 AM, Dibyendu Majumdar ***@***.***> wrote:
> 
> 
> Hi,
> 
> Thank you for the cool project.
> I am running the netlib tests and I see some cases of failures; I was wondering if you have a list of test results that I can compare against.
> 
> Regards
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 



-- 
Dr Geoff Leyland - ***@***.***
Incremental Limited
+64 21 717 432
http://www.incremental.co.nz/

**Comment by dibyendumajumdar** [comment]
Great, thank you.
